INSERT INTO TRUCK(ID, CREATION_DATE, LICENSE_PLATE, MANUFACTURER, MONTH, YEAR) VALUES (1, CURRENT_TIMESTAMP(), 'AA-11-AA', 'MAN', 7, 2020);
INSERT INTO TRUCK(ID, CREATION_DATE, LICENSE_PLATE, MANUFACTURER, MONTH, YEAR) VALUES (2, CURRENT_TIMESTAMP(), '11-BB-11', 'MAN', 7, 2020);



INSERT INTO GEO_RECORD(ID , CREATION_DATE , LNG , LAT , TRUCK_ID) VALUES (1  , CURRENT_TIMESTAMP() , -9.14484 , 38.73412 , 1);
INSERT INTO GEO_RECORD(ID , CREATION_DATE , LNG , LAT , TRUCK_ID) VALUES (2  , CURRENT_TIMESTAMP() , -9.14576 , 38.73782 , 1);
INSERT INTO GEO_RECORD(ID , CREATION_DATE , LNG , LAT , TRUCK_ID) VALUES (3  , CURRENT_TIMESTAMP() , -9.14606 , 38.73903 , 1);
INSERT INTO GEO_RECORD(ID , CREATION_DATE , LNG , LAT , TRUCK_ID) VALUES (4  , CURRENT_TIMESTAMP() , -9.14635 , 38.74043 , 1);


